esphome:
  name: wasserzahler
  friendly_name: Wasserzähler

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "[yourkey]"

ota:
  - platform: esphome
    password: "[yourkey]"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wasserzahler Fallback Hotspot"
    password: "[yourkey]"

captive_portal:

esp32_camera:
  name: Wasserzähler Kamera
  id: wasserzahler_cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: SVGA  # Höhere Auflösung
  jpeg_quality: 8   # Bessere Qualität
  vertical_flip: False
  horizontal_mirror: False

# Optional: LED für Ausleuchtung
output:
  - platform: gpio
    pin: GPIO4
    id: cam_led

light:
  - platform: binary
    output: cam_led
    name: "Wasserzähler LED"
